name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - uses: actions/setup-python@v4.5.0
      with:
        python-version: "3.10"

    - name: Run Python Script
      run: python git_script.py

    - name: Auto Commit
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Auto commit via GitHub Actions"
        git push origin main  # adjust the branch as needed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}